name: Update RLIs
on:
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Starlight220/InspectRLIs@e116358fca786407b3be759ee3260a0769c3b35d
        with:
          root: .
          baseUrl: https://raw.githubusercontent.com/wpilibsuite/allwpilib/
          versionScheme: v\\d{4}\\.\\d\\.\\d(?:-beta-\\d)?
          latestVersion: v2021.3.1
      - run: git diff
